[workspace]
resolver = "3"
members = ["primitives", "preview", "test-harness", "dioxus-attributes"]

[workspace.dependencies]
dioxus-primitives = { path = "primitives" }
dioxus-test = { git = "https://github.com/hovinen/dioxus-test", branch = "show-element-with-focus-in-failure-message-for-has-focus" }
tracing = { version = "0.1", features = ["std"] }

dioxus = { version = "0.8.0-alpha.1", git = "https://github.com/hovinen/dioxus", branch = "add-synthetic-form-event" }
dioxus-icons = { git = "https://github.com/hovinen/dioxus-icons", branch = "0.8-alpha.1" }
dioxus-i18n = { git = "https://github.com/hovinen/dioxus-i18n", branch = "0.8-alpha.1" }
dioxus-rsx = { version = "0.8.0-alpha.1", git = "https://github.com/hovinen/dioxus", branch = "add-synthetic-form-event" }
dioxus-ssr = { version = "0.8.0-alpha.1", git = "https://github.com/hovinen/dioxus", branch = "add-synthetic-form-event" }

[patch.crates-io]
blitz-dom = { git = "https://github.com/hovinen/blitz", branch = "support-setting-hidden-flag" }
blitz-traits = { git = "https://github.com/hovinen/blitz", branch = "support-setting-hidden-flag" }

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
strip = true
incremental = false

[profile.dev]
debug = 0

[profile.dev.build-override]
opt-level = 3
codegen-units = 1
